// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package pgxstore

import (
	"context"

	pgxstore "github.com/Kopleman/metcol/internal/server/pgxstore/models"
)

type Querier interface {
	CreateMetric(ctx context.Context, arg CreateMetricParams) (*pgxstore.Metric, error)
	ExistsMetric(ctx context.Context, arg ExistsMetricParams) (bool, error)
	GetAllMetrics(ctx context.Context) ([]*pgxstore.Metric, error)
	GetMetric(ctx context.Context, arg GetMetricParams) (*pgxstore.Metric, error)
	UpdateMetric(ctx context.Context, arg UpdateMetricParams) error
}

var _ Querier = (*Queries)(nil)
